### ISSUE TITLE
viewport should not move when viewing livestream chat history and new messages arrive

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#67]
I'm using the Livestream chat type, and our customers and clients are complaining that when many people are on the channel, new messages move the viewport. This makes it hard to edit or delete messages when there are many people chatting, because the viewport is moving around so many times per minute.

The standard idiom in chat (see skype, slack, etc) is that when you scroll into the chat history, the viewport stays put so that the messages you are looking at do not move around.

This is a serious issue for our clients, as they cannot easily read back through the history during the livestream session to moderate posts or to synthesize comments.

Can you recommend a workaround for us until this is fixed?

UPDATE: 

python:
stream-chat==0.4.3

js: 
stream-chat-react==0.6.20
stream-chat==1.0.4

**Comment by tbarbugli** [comment]
@codekiln thank you for reporting this problem; what you describe is a bug on the React Native SDK, the intended behavior is indeed what you describe (auto scroll on new messages only when the message list is not at the bottom).

**Comment by vishalnarkhede** [comment]
Hey @codekiln ,

This has been fixed in v0.7.8. Please confirm if it solves the problem for you :)

**Comment by codekiln** [comment]
@vishalnarkhede Thank you! Testing in progress.

**Comment by codekiln** [comment]
Unfortunately, this issue is still reproducible for me. 

NPM: 
```
"stream-chat": "1.1.6",
"stream-chat-react": "0.7.8",
```

Python pip:
```
stream-chat==0.5.0
```

Viewport of 2nd user's window **before** posting message with user 1: 
![before image - top of image includes the phrase "Last Wednesday" at the top](https://user-images.githubusercontent.com/140930/66847491-74066680-ef41-11e9-8381-903effa7acd6.png)

Viewport of 2nd user's window **after** posting message with user 1:
![after image - top of image no longer includes the phrase "Last Wednesday" at the top.](https://user-images.githubusercontent.com/140930/66847602-aca64000-ef41-11e9-9cc4-c62968bd17ac.png)

Note that in the first message the heading "Last Wednesday" is at the top of the viewport, and after user 1 posted a message, user 2 no longer has the heading "Last Wednesday" at the top; it has scrolled up.

**Comment by codekiln** [comment]
Some more info about this example: 

```
>>> /* before adding message */ console.log({scrollTop: document.querySelector('.str-chat__list').scrollTop, offsetHeight: document.querySelector('.str-chat__list').offsetHeight})
VM23262:1 {scrollTop: 3559, offsetHeight: 671}
undefined
>>> /* after adding message */ console.log({scrollTop: document.querySelector('.str-chat__list').scrollTop, offsetHeight: document.querySelector('.str-chat__list').offsetHeight})
VM23278:1 {scrollTop: 3701, offsetHeight: 671}
```

**Comment by vishalnarkhede** [comment]
@codekiln Does it only happen when first new message arrives? Or with every new message it keeps scrolling up?

Following is the scenario:

MW - Message Window
1. Scroll up in MW-1
2. Send a message from MW-2 (at this point you I think see the shifting in viewport)
3. Send few more messages from MW-2 - At this point do you still see the movement or scrolling in MW-1?

**Comment by codekiln** [comment]
Hi @vishalnarkhede, with your described scenario, it keeps scrolling _down_ with each new message that arrives. 

Tested in the JS console with the following snippet:  
```
`scroll top is at ${100 - (document.querySelector('.str-chat__list').scrollTop * 100 / document.querySelector('.str-chat__reverse-infinite-scroll').scrollHeight).toFixed(2)}% from bottom to top` 
```

## Starting point
`"scroll top is at 62.11% from bottom to top"`
![image](https://user-images.githubusercontent.com/140930/66927240-77f7be80-effd-11e9-8c5c-7a06ef64d881.png)

## message 1 arrives
`"scroll top is at 60.72% from bottom to top"`
![image](https://user-images.githubusercontent.com/140930/66927386-b7bea600-effd-11e9-92ab-0e8ec37da966.png)

## message 2 arrives
`"scroll top is at 59.91% from bottom to top"`
![image](https://user-images.githubusercontent.com/140930/66927454-d91f9200-effd-11e9-96e9-daf4aa807a53.png)

## message 3 arrives
`"scroll top is at 59.12% from bottom to top"`
![image](https://user-images.githubusercontent.com/140930/66927541-f6ecf700-effd-11e9-8e42-30ae3dac4ef2.png)

## context
```
return <Chat client={client} theme={'messaging light'}>
  <Channel channel={channel} maxNumberOfFiles={maxNumberOfFiles}>
    <Window hideOnThread>
      <PinnedMessage channel={channel} client={client}/>
      <MessageList Message={MessageLivestream} messageActions={CUSTOM_MESSAGE_ACTIONS} HeaderComponent={PinnedMessage} EmptyStateIndicator={LoadingIndicator}/>
      <MessageInput/>
    </Window>
  </Channel>
</Chat>;
```

**Comment by vishalnarkhede** [comment]
Hey @codekiln,

Sorry for the miscommunication. Unfortunately fix was not published as part of v0.7.8. 
I have just published a new version of our sdk - v0.7.9 which contains that fix.

Please check and let us know if it fixes the issue :)

**Comment by codekiln** [comment]
Thanks @vishalnarkhede - testing in progress.
